/**
 * F182-4b / ADR-0030 Amendment B — `rotateCommitteeKeyOnRemovalViaProduction`,
 * the client-side key-rotation-on-removal composition (Decisions B2–B6).
 *
 * RED-FIRST (TDD). The implementer treats this file as READ-ONLY. The
 * composition does NOT exist yet, so every test is RED at the composition-
 * exists guard (`getComposition()` asserts the export is a function) — a
 * SPECIFIC red naming what is missing. The observable-contract assertions
 * below the guard are the GREEN target the implementer builds to.
 *
 * ───────────────────────────────────────────────────────────────────────────
 * THE CONTRACT PINNED (ADR-0030 Amendment B, decisions.md ~:10419 +
 * threat-model.md F182-4 DESIGN VALIDATION ~:4749)
 * ───────────────────────────────────────────────────────────────────────────
 * The composition sequences (fresh path, Decision B3):
 *   (1) precondition — hasLiveKey or latch-guarded unwrap+set (fail-fast).
 *   (2) rotate            → rotate_committee_data_key('member_removal')
 *                           → { rotation_id, new_key_id }.
 *   (3) revoke (EARLY)    → revoke_committee_member(removed, rotation_id).
 *   (4) SELF-WRAP FIRST   → newKey = randombytes_buf(32); seal(newKey, self_pub);
 *                           wrap_member(self, new_key_id, …, rotation_id);
 *                           .fill(0) newKey in a finally.
 *   (5) INSTALL new LIVE  → unwrapAll → holder.populate({old:retired,new:live}).
 *   (6) RE-WRAP LOOP      → per remaining member: get_member_pubkey →
 *                           wrapMemberInViaProduction({…,rotation_id}) (seals the
 *                           NEW live key). member_not_enrolled → SKIP → pending.
 *   (7) finalize          → finalize_committee_data_key_rotation(rotation_id,
 *                           new_key_id, count = 1(self) + rewrapped).
 *   (8) zeroize / dwell.
 *
 * Fail-LOUD union (Decision B5): NEVER `ok` unless the self-wrap landed AND
 * `finalize` succeeded.
 *   ok                       — self-wrap + all remaining re-wrapped + finalize.
 *   ok_with_pending          — finalized, ≥1 remaining offline/unenrolled.
 *   orphaned                 — rotate landed, self-wrap did NOT (zero-wrap epoch).
 *   incomplete               — self-wrap OK, a re-wrap/finalize failed (resumable).
 *   cannot_resume_not_holder — a resumer who holds NO new-epoch wrap.
 *   failed                   — precondition / rotate-denied / revoke-denied.
 *
 * Opts follow the ADR (Decision B3) + the sibling production-flows conventions:
 *   { client, holder, localIdentity, user_id (actor), actor_public_key,
 *     removed_member_id, remaining_members:[{user_id}], resume?:{rotation_id,new_key_id} }
 *
 * ───────────────────────────────────────────────────────────────────────────
 * TEST → AC / TM / re-pass-trigger MAP (grouped by category below)
 * ───────────────────────────────────────────────────────────────────────────
 *   Happy path     — AC-B2, AC-B3 · TM-1, TM-2, TM-7, TM-9, TM-11.
 *   Forward-secrecy— TM-7 / B1-seals-new-key · Decision B6.
 *   Ordering       — AC-B2 · TM-1 · re-pass #21 / #21(a).
 *   Orphan crash   — AC-B7 · TM-4 · re-pass #21, #22.
 *   Incomplete/read— AC-B4, AC-B8 · TM-3.
 *   Resumability   — AC-B6 · TM-5 · re-pass #24.
 *   Fail-loud      — AC-B8 · TM-6 · re-pass #22.
 *   Merged-guard   — AC-B10 · TM-8 · F-VAL-1(b)/F-196/F-195 · re-pass #25.
 *   Concurrency    — AC-B12 · TM-13 · R1.
 *   ≥1-active guard— rotate `no_active_members`.
 *   Offline edge   — AC-B11 · TM-12.
 *   Zeroize/no-log — AC-B9 · TM-10 · re-pass #25.
 *   No escalation  — AC-B13 · TM-9 · re-pass #15 carry.
 *   Fan-out/detect — TM-11 · F-188 · R2.
 *   R3 fail-closed — TM-7 fail-closed · R3 (omit new_key_id at step 5).
 *
 * DETERMINISM: no real clock, no real network, no seeded-RNG assertions. Random
 * key bytes are generated by real libsodium but are NEVER asserted-on by value —
 * only by zeroization / round-trip. Crash + session-end-wipe injection is
 * deterministic via transport op hooks + holder wipe calls (NOT timers), honoring
 * the F-190 lesson (deterministic injection, never wall-clock timing). Each test
 * owns its fixtures; nothing is shared mutable.
 */

import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import _sodium from 'libsodium-wrappers-sumo';
import {
  BrowserLocalIdentityStore,
  CommitteeKeyHolder,
  SupabaseT07Client,
  pubkeyFingerprint,
  type T07OpTransport
} from '../../src/lib/crypto';
import * as cryptoLib from '../../src/lib/crypto';
import { __getCapturedLines, __resetCapture, __setTestSink } from '../../src/lib/log/test-sink';

await _sodium.ready;
const sodium = _sodium;

// Synthetic uids (no PI).
const ACTOR = '9f4e9b40-0000-4000-8000-00000000001a'; // co-chair running the removal
const M1 = '9f4e9b40-0000-4000-8000-00000000002b'; // remaining active member
const M2 = '9f4e9b40-0000-4000-8000-00000000003c'; // remaining active member
const REMOVED = '9f4e9b40-0000-4000-8000-00000000004d'; // the removed (now inactive) member
const RESUMER_B = '9f4e9b40-0000-4000-8000-00000000005e'; // resumer WHO HOLDS a new-epoch wrap
const RESUMER_C = '9f4e9b40-0000-4000-8000-00000000006f'; // resumer with NO new-epoch wrap
const RESUMER_D = '9f4e9b40-0000-4000-8000-000000000070'; // resumer with server-side wraps but NO local privkey

const OLD_KEY_ID = 'k-epoch-1';
const OLD_EPOCH = 7;

// ───────────────────────────────────────────────────────────────────────────
// pg-hex helpers (mirror the sibling T07 tests).
// ───────────────────────────────────────────────────────────────────────────
function bytesToPgHex(b: Uint8Array): string {
  let s = '\\x';
  for (const v of b) s += v.toString(16).padStart(2, '0');
  return s;
}
function pgHexToBytes(h: string): Uint8Array {
  const body = h.startsWith('\\x') ? h.slice(2) : h;
  return new Uint8Array(body.match(/.{1,2}/g)!.map((x) => parseInt(x, 16)));
}
function silentStore(): BrowserLocalIdentityStore {
  return new BrowserLocalIdentityStore({ idbFactory: null, warn: () => undefined });
}
function isAllZero(b: Uint8Array): boolean {
  return b.every((x) => x === 0);
}

// ───────────────────────────────────────────────────────────────────────────
// Composition-under-test resolver — namespace access so a MISSING export reads
// `undefined` (per-test specific RED) rather than a module-load link error.
// ───────────────────────────────────────────────────────────────────────────
interface RemainingMember {
  user_id: string;
}
interface RotateOnRemovalOpts {
  client: SupabaseT07Client;
  holder: CommitteeKeyHolder;
  localIdentity: BrowserLocalIdentityStore;
  user_id: string;
  actor_public_key: Uint8Array;
  removed_member_id: string;
  remaining_members: RemainingMember[];
  resume?: { rotation_id: string; new_key_id: string };
}
type RotateOnRemovalResult = { status: string; [k: string]: unknown };

function getComposition(): (opts: RotateOnRemovalOpts) => Promise<RotateOnRemovalResult> {
  const fn = (cryptoLib as Record<string, unknown>).rotateCommitteeKeyOnRemovalViaProduction;
  expect(
    typeof fn,
    'RED (F182-4b): `rotateCommitteeKeyOnRemovalViaProduction` is not exported from ' +
      'src/lib/crypto — the ADR-0030 Amendment B composition (Decisions B2/B3/B5) does not ' +
      'exist yet. The implementer builds it to satisfy the observable-contract assertions below.'
  ).toBe('function');
  return fn as (opts: RotateOnRemovalOpts) => Promise<RotateOnRemovalResult>;
}
function runRotation(opts: RotateOnRemovalOpts): Promise<RotateOnRemovalResult> {
  return getComposition()(opts);
}

// ───────────────────────────────────────────────────────────────────────────
// A member fixture — a real keypair + its REAL SHA-256 pubkey fingerprint (so
// the re-wrap's self-consistency assert inside `wrapMemberInViaProduction`
// genuinely re-derives-and-matches).
// ───────────────────────────────────────────────────────────────────────────
interface MemberFixture {
  user_id: string;
  pub: Uint8Array;
  priv: Uint8Array;
  fingerprint: string;
  active: boolean;
}
async function makeMember(user_id: string, active: boolean): Promise<MemberFixture> {
  const kp = sodium.crypto_box_keypair();
  const fingerprint = await pubkeyFingerprint(kp.publicKey);
  return { user_id, pub: kp.publicKey, priv: kp.privateKey, fingerprint, active };
}

// ───────────────────────────────────────────────────────────────────────────
// FakeKeyServer — a stateful model of the migration-0007 RPCs the composition
// orchestrates: epoch table (live = rotated_at IS NULL), the committee_key_wraps
// table, member identities, and the rotation records. Faithful to the contract
// pins in ADR-0030 Amendment B (the file:line notes in decisions.md/threat-model).
// ───────────────────────────────────────────────────────────────────────────
interface EpochRow {
  key_id: string;
  epoch: number;
  rotated_at: number | null;
}
interface WrapRow {
  member: string;
  key_id: string;
  sealed: Uint8Array;
  rotation_id: string | null;
}
interface RotationRow {
  rotation_id: string;
  new_key_id: string;
  started: boolean;
  finalized: boolean;
}
type Wire = { status: number; body: unknown };
function wireOk(data: unknown): Wire {
  return { status: 200, body: { ok: true, data } };
}
function wireErr(reason: string, status: number): Wire {
  return { status, body: { ok: false, error: reason } };
}

class FakeKeyServer {
  epochs: EpochRow[] = [];
  wraps: WrapRow[] = [];
  identities = new Map<string, MemberFixture>();
  rotations = new Map<string, RotationRow>();
  /** The JWT subject the self-scoped ops (get_all_key_wraps / get_key_wrap /
   *  committee_key_state) resolve against. Default the actor; resume tests
   *  point it at the resumer. */
  selfUserId = ACTOR;
  /** ≥1-active-member guard input (rotate refuses when < 1). */
  activeMemberCount = 3;
  /** Per-target pubkey substitution (R2 self-detect): member → substitute keypair. */
  substitutePubkey = new Map<string, { pub: Uint8Array; fingerprint: string }>();
  #seq = 100;
  #epochN = 1;
  #rotN = 1;

  liveEpoch(): EpochRow | undefined {
    return this.epochs.find((e) => e.rotated_at === null);
  }
  seedEpoch(key_id: string, epoch: number, rotated_at: number | null): void {
    this.epochs.push({ key_id, epoch, rotated_at });
  }
  seedWrap(member: string, key_id: string, sealed: Uint8Array): void {
    this.wraps.push({ member, key_id, sealed, rotation_id: null });
  }
  wrapsOf(member: string): WrapRow[] {
    return this.wraps.filter((w) => w.member === member);
  }
  wrapOn(member: string, key_id: string): WrapRow | undefined {
    return this.wraps.find((w) => w.member === member && w.key_id === key_id);
  }

  /** rotate_committee_data_key — retire live, mint epoch+1, start a rotation. */
  rotate(): Wire {
    if (this.activeMemberCount < 1) return wireErr('no_active_members', 400); // :583-585
    const live = this.liveEpoch();
    if (live) live.rotated_at = ++this.#seq; // :588-592 marks prev rotated_at
    const new_key_id = `k-epoch-${++this.#epochN}`;
    const epoch = (live?.epoch ?? OLD_EPOCH) + 1;
    this.epochs.push({ key_id: new_key_id, epoch, rotated_at: null }); // :595-596
    const rotation_id = `rot-${this.#rotN++}`;
    this.rotations.set(rotation_id, { rotation_id, new_key_id, started: true, finalized: false });
    return wireOk({ rotation_id, new_key_id });
  }

  /** Concurrency R1: a SECOND rotate landing during the first's client tail —
   *  retires whatever is currently live (the first ceremony's new epoch). */
  concurrentRotate(): void {
    const live = this.liveEpoch();
    if (live) live.rotated_at = ++this.#seq;
    const new_key_id = `k-epoch-${++this.#epochN}`;
    const epoch = (live?.epoch ?? OLD_EPOCH) + 1;
    this.epochs.push({ key_id: new_key_id, epoch, rotated_at: null });
  }

  /** revoke_committee_member — archive→DELETE the removed member's wraps across
   *  ALL epochs (:699-706). Does NOT touch membership. */
  revoke(removed: string): Wire {
    const before = this.wraps.length;
    this.wraps = this.wraps.filter((w) => w.member !== removed);
    return wireOk({ wraps_removed: before - this.wraps.length });
  }

  /** wrap_committee_data_key_for_member — active-target gate (:502-503) +
   *  key-exists gate + ON CONFLICT (user_id,key_id) DO NOTHING (:509-511). */
  wrapMember(member: string, key_id: string, sealedHex: string, rotation_id: string | null): Wire {
    const id = this.identities.get(member);
    if (!id || !id.active) return wireErr('rls_denied', 403); // :502-503 active-target gate
    if (!this.epochs.some((e) => e.key_id === key_id)) return wireErr('not_found', 404);
    if (this.wrapOn(member, key_id)) return wireOk(null); // ON CONFLICT DO NOTHING (idempotent)
    this.wraps.push({ member, key_id, sealed: pgHexToBytes(sealedHex), rotation_id });
    return wireOk(null);
  }

  /** get_all_committee_key_wraps_for_self — every self wrap across live+retired. */
  getAllWraps(): Wire {
    const rows = this.wrapsOf(this.selfUserId).map((w) => {
      const e = this.epochs.find((x) => x.key_id === w.key_id)!;
      return {
        key_id: w.key_id,
        epoch: e.epoch,
        wrapped_ciphertext_hex: bytesToPgHex(w.sealed),
        is_live: e.rotated_at === null
      };
    });
    return wireOk(rows);
  }

  /** get_committee_key_wrap_for_self — the self LIVE-epoch wrap (step-1 unwrap). */
  getKeyWrap(): Wire {
    const live = this.liveEpoch();
    if (!live) return wireOk(null);
    const w = this.wrapOn(this.selfUserId, live.key_id);
    if (!w) return wireOk(null);
    return wireOk({
      key_id: live.key_id,
      epoch: live.epoch,
      wrapped_ciphertext_hex: bytesToPgHex(w.sealed)
    });
  }

  /** committee_key_state_for_self — live metadata + actor_has_wrap. */
  keyState(): Wire {
    const live = this.liveEpoch();
    if (!live) return wireOk(null);
    const wrapCount = this.wraps.filter((w) => w.key_id === live.key_id).length;
    return wireOk({
      key_id: live.key_id,
      epoch: live.epoch,
      wrap_count: wrapCount,
      actor_has_wrap: !!this.wrapOn(this.selfUserId, live.key_id)
    });
  }

  /** get_member_pubkey — enrolled+active target → {pubkey, fingerprint};
   *  else member_not_enrolled (F-174 closed collapse). Honors substitution. */
  memberPubkey(target: string): Wire {
    const sub = this.substitutePubkey.get(target);
    if (sub) return wireOk({ public_key_hex: bytesToPgHex(sub.pub), fingerprint: sub.fingerprint });
    const id = this.identities.get(target);
    if (!id || !id.active) return wireErr('member_not_enrolled', 403);
    return wireOk({ public_key_hex: bytesToPgHex(id.pub), fingerprint: id.fingerprint });
  }

  /** finalize_committee_data_key_rotation — pair against .started, and the new
   *  key must be UN-rotated-out (:650-653 → the R1 `invalid_new_key` case). */
  finalize(rotation_id: string, new_key_id: string): Wire {
    const r = this.rotations.get(rotation_id);
    if (!r || !r.started || r.finalized) return wireErr('rotation_not_started', 409);
    const e = this.epochs.find((x) => x.key_id === new_key_id);
    if (!e || e.rotated_at !== null) return wireErr('invalid_new_key', 409); // :650-653
    r.finalized = true;
    return wireOk(null);
  }
}

// ───────────────────────────────────────────────────────────────────────────
// Deterministic transport with op hooks. `onOp` fires SIDE-EFFECTS (session-end
// wipe / concurrent rotate) synchronously inside a chosen op+occurrence; `override`
// forces a fault (error body) or `'throw'`. No timers; the injection point is the
// op the composition is suspended on.
// ───────────────────────────────────────────────────────────────────────────
type OverrideResult = Wire | 'throw' | undefined;
interface TransportHooks {
  onOp?: (op: string, occurrence: number, body: Record<string, unknown>) => void;
  override?: (op: string, occurrence: number, body: Record<string, unknown>) => OverrideResult;
}
interface RecordedOp {
  op: string;
  occurrence: number;
  body: Record<string, unknown>;
}
function makeTransport(
  srv: FakeKeyServer,
  hooks: TransportHooks = {}
): { transport: T07OpTransport; ops: RecordedOp[] } {
  const ops: RecordedOp[] = [];
  const counts: Record<string, number> = {};
  const transport: T07OpTransport = async (body) => {
    const op = String(body.op);
    const occurrence = counts[op] ?? 0;
    counts[op] = occurrence + 1;
    ops.push({ op, occurrence, body });
    hooks.onOp?.(op, occurrence, body);
    const ov = hooks.override?.(op, occurrence, body);
    if (ov === 'throw') throw new Error(`injected transport throw on ${op}#${occurrence}`);
    if (ov) return ov;
    switch (op) {
      case 'rotate':
        return srv.rotate();
      case 'revoke_member':
        return srv.revoke(String(body.removed_member_id));
      case 'wrap_member':
        return srv.wrapMember(
          String(body.member_user_id),
          String(body.key_id),
          String(body.wrapped_ciphertext_hex),
          (body.rotation_id as string | null) ?? null
        );
      case 'get_all_key_wraps':
        return srv.getAllWraps();
      case 'get_key_wrap':
        return srv.getKeyWrap();
      case 'committee_key_state':
        return srv.keyState();
      case 'get_member_pubkey':
        return srv.memberPubkey(String(body.target_user_id));
      case 'finalize_rotate':
        return srv.finalize(String(body.rotation_id), String(body.new_key_id));
      default:
        throw new Error(`makeTransport: unexpected op ${op}`);
    }
  };
  return { transport, ops };
}

// ───────────────────────────────────────────────────────────────────────────
// Standard committee fixture: an old live epoch (k-epoch-1) with self + M1 + M2
// + REMOVED wraps; ACTOR/M1/M2 active, REMOVED inactive (membership already
// flipped by F182-6 before the composition runs).
// ───────────────────────────────────────────────────────────────────────────
interface Committee {
  srv: FakeKeyServer;
  localIdentity: BrowserLocalIdentityStore;
  actor: MemberFixture;
  m1: MemberFixture;
  m2: MemberFixture;
  removed: MemberFixture;
  oldKey: Uint8Array;
}
async function setupCommittee(): Promise<Committee> {
  const srv = new FakeKeyServer();
  srv.seedEpoch(OLD_KEY_ID, OLD_EPOCH, null);
  const localIdentity = silentStore();

  const actor = await makeMember(ACTOR, true);
  const m1 = await makeMember(M1, true);
  const m2 = await makeMember(M2, true);
  const removed = await makeMember(REMOVED, false);
  for (const m of [actor, m1, m2, removed]) srv.identities.set(m.user_id, m);
  await localIdentity.storeIdentityPrivateKey(ACTOR, actor.priv);

  // Old-epoch wraps (each member sealed the old key under their own pubkey).
  const oldKey = sodium.randombytes_buf(sodium.crypto_secretbox_KEYBYTES);
  srv.seedWrap(ACTOR, OLD_KEY_ID, sodium.crypto_box_seal(oldKey, actor.pub));
  srv.seedWrap(M1, OLD_KEY_ID, sodium.crypto_box_seal(oldKey, m1.pub));
  srv.seedWrap(M2, OLD_KEY_ID, sodium.crypto_box_seal(oldKey, m2.pub));
  srv.seedWrap(REMOVED, OLD_KEY_ID, sodium.crypto_box_seal(oldKey, removed.pub));
  srv.activeMemberCount = 3;
  return { srv, localIdentity, actor, m1, m2, removed, oldKey };
}

function standardOpts(
  c: Committee,
  client: SupabaseT07Client,
  holder: CommitteeKeyHolder,
  extra?: Partial<RotateOnRemovalOpts>
): RotateOnRemovalOpts {
  return {
    client,
    holder,
    localIdentity: c.localIdentity,
    user_id: ACTOR,
    actor_public_key: c.actor.pub,
    removed_member_id: REMOVED,
    remaining_members: [{ user_id: M1 }, { user_id: M2 }],
    ...extra
  };
}

// Open the actor's self-wrap on the new epoch → recover the fresh new key bytes.
function recoverNewKey(srv: FakeKeyServer, actor: MemberFixture, newKeyId: string): Uint8Array {
  const w = srv.wrapOn(ACTOR, newKeyId);
  if (!w) throw new Error('no self-wrap on the new epoch to recover the new key from');
  return sodium.crypto_box_seal_open(w.sealed, actor.pub, actor.priv);
}
// The new_key_id the composition minted == the key_id it self-wrapped under.
function newKeyIdFrom(ops: RecordedOp[]): string {
  const selfWrap = ops.find((o) => o.op === 'wrap_member');
  if (!selfWrap) throw new Error('no wrap_member op recorded');
  return String(selfWrap.body.key_id);
}
function opIndex(ops: RecordedOp[], pred: (o: RecordedOp) => boolean): number {
  return ops.findIndex(pred);
}

// A secretbox record sealed under a data key — the "existing data" probe.
interface Record0 {
  nonce: Uint8Array;
  ct: Uint8Array;
  pt: string;
}
function sealRecord(pt: string, key: Uint8Array): Record0 {
  const nonce = sodium.randombytes_buf(sodium.crypto_secretbox_NONCEBYTES);
  const ct = sodium.crypto_secretbox_easy(new Uint8Array(new TextEncoder().encode(pt)), nonce, key);
  return { nonce, ct, pt };
}
async function tryReadRecord(holder: CommitteeKeyHolder, rec: Record0): Promise<string | null> {
  const r = await holder.trialOpen<string>((k) => {
    const pt = sodium.crypto_secretbox_open_easy(rec.ct, rec.nonce, k); // throws on wrong key
    return new TextDecoder().decode(pt);
  });
  return r.status === 'ok' ? r.value : null;
}

beforeEach(() => {
  __resetCapture();
  __setTestSink();
});
afterEach(() => {
  __resetCapture();
  vi.restoreAllMocks();
});

// ===========================================================================
// HAPPY PATH — AC-B2 / AC-B3 · TM-1, TM-2, TM-7, TM-9, TM-11
// ===========================================================================
describe('F182-4b happy path — AC-B2/AC-B3: full rotate→revoke→self-wrap→populate→re-wrap→finalize', () => {
  it('AC-B2: returns ok, installs the new epoch live, finalize carries count=3 (self+M1+M2)', async () => {
    const c = await setupCommittee();
    const { transport, ops } = makeTransport(c.srv);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH }); // pre-seed → step 1 skipped

    const r = await runRotation(standardOpts(c, client, holder));

    expect(r.status, 'AC-B2: a full clean rotation must return ok').toBe('ok');
    const newKeyId = newKeyIdFrom(ops);
    expect(newKeyId).not.toBe(OLD_KEY_ID);
    // New epoch is the holder's live key; the old epoch is retained (anti-lockout).
    expect(holder.getKeyId(), 'AC-B2: the new epoch is the holder live key').toBe(newKeyId);
    expect(holder.hasLiveKey()).toBe(true);
    expect(holder.size(), 'AC-B2: holder retains old(retired)+new(live)').toBeGreaterThanOrEqual(2);
    // finalize carries count = 1(self) + 2(M1,M2).
    const fin = ops.find((o) => o.op === 'finalize_rotate');
    expect(fin, 'AC-B2: finalize_rotate must be called').toBeDefined();
    expect(fin!.body.new_key_id).toBe(newKeyId);
    expect(
      fin!.body.members_rewrapped_count,
      'AC-B2: finalize count = 1 self-wrap + 2 remaining re-wraps = 3'
    ).toBe(3);
  });

  it('AC-B2/TM-11: every remaining member gets a wrap under new_key_id carrying the rotation_id; removed member gets NONE', async () => {
    const c = await setupCommittee();
    const { transport, ops } = makeTransport(c.srv);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    const r = await runRotation(standardOpts(c, client, holder));
    expect(r.status).toBe('ok');
    const newKeyId = newKeyIdFrom(ops);

    // The rotation_id threaded onto every wrap_member + finalize (audit pair).
    const rotateBody = ops.find((o) => o.op === 'rotate');
    expect(rotateBody).toBeDefined();
    const wraps = ops.filter((o) => o.op === 'wrap_member');
    expect(wraps.length, 'TM-11: N wrapped_for_member incl self = 1 self + 2 remaining').toBe(3);
    for (const w of wraps) {
      expect(w.body.key_id, 'every wrap is under the NEW epoch').toBe(newKeyId);
      expect(
        typeof w.body.rotation_id === 'string' && (w.body.rotation_id as string).length > 0,
        'AC-B2/B1: every re-wrap carries the live rotation_id (not null) so the audit pair reconstructs'
      ).toBe(true);
    }
    // M1 and M2 each got exactly one new-epoch wrap.
    expect(c.srv.wrapOn(M1, newKeyId), 'M1 re-wrapped under new epoch').toBeDefined();
    expect(c.srv.wrapOn(M2, newKeyId), 'M2 re-wrapped under new epoch').toBeDefined();
    // The removed member got NO new-epoch wrap and no wraps at all (purged).
    expect(
      c.srv.wrapOn(REMOVED, newKeyId),
      'AC-B2: the removed member must NEVER receive a new-epoch wrap'
    ).toBeUndefined();
    expect(
      c.srv.wrapsOf(REMOVED).length,
      'AC-B5/purge: the removed member holds zero wraps after revoke'
    ).toBe(0);
  });

  it('AC-B3/TM-2: the self-wrap is the FIRST wrap on the new epoch (no zero-wrap orphan window past self-wrap)', async () => {
    const c = await setupCommittee();
    const { transport, ops } = makeTransport(c.srv);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    const r = await runRotation(standardOpts(c, client, holder));
    expect(r.status).toBe('ok');
    const newKeyId = newKeyIdFrom(ops);

    const firstWrap = ops.find((o) => o.op === 'wrap_member')!;
    expect(
      firstWrap.body.member_user_id,
      'AC-B3: the FIRST wrap_member on the new epoch must be the actor self-wrap'
    ).toBe(ACTOR);
    expect(firstWrap.body.key_id).toBe(newKeyId);
    // The self-wrap opens (with the actor privkey) to a 32-byte key → recoverable.
    const recovered = recoverNewKey(c.srv, c.actor, newKeyId);
    expect(recovered.length).toBe(32);
    expect(isAllZero(recovered), 'the self-wrapped new key is real (non-zero) key material').toBe(
      false
    );
  });
});

// ===========================================================================
// FORWARD-SECRECY / SEAL-UNDER-NEW-KEY — TM-7 (B1 seals the NEW key) · Decision B6
// ===========================================================================
describe('F182-4b forward-secrecy — TM-7: every re-wrap seals the NEW epoch key, never the old live key', () => {
  it('each remaining member`s wrap opens (with their own privkey) to the NEW key bytes, and the new key != the old key', async () => {
    const c = await setupCommittee();
    const { transport, ops } = makeTransport(c.srv);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });
    // Snapshot the old key bytes BEFORE the run (populate may zeroize the seed buffer).
    const oldKeyBytes = Array.from(c.oldKey);

    const r = await runRotation(standardOpts(c, client, holder));
    expect(r.status).toBe('ok');
    const newKeyId = newKeyIdFrom(ops);
    const newKey = recoverNewKey(c.srv, c.actor, newKeyId);

    // The NEW key is genuinely new, not the old live key.
    expect(
      Array.from(newKey),
      'TM-7/B6: the sealed new-epoch key must differ from the pre-rotation live key'
    ).not.toEqual(oldKeyBytes);

    // M1 and M2 open their new-epoch wraps to EXACTLY the new key (forward secrecy).
    for (const m of [c.m1, c.m2]) {
      const w = c.srv.wrapOn(m.user_id, newKeyId)!;
      const opened = sodium.crypto_box_seal_open(w.sealed, m.pub, m.priv);
      expect(
        Array.from(opened),
        `TM-7: ${m.user_id}'s re-wrap must seal the NEW key (never the old live key)`
      ).toEqual(Array.from(newKey));
      expect(Array.from(opened), 'and must NOT be the old key').not.toEqual(oldKeyBytes);
    }
  });
});

// ===========================================================================
// ORDERING — AC-B2 · TM-1 · re-pass #21 / #21(a)
// ===========================================================================
describe('F182-4b ordering — TM-1/re-pass #21: rotate→revoke→self-wrap→populate→re-wrap→finalize', () => {
  it('the transport op-order is exactly the co-signed sequence; revoke precedes any wrap; populate precedes any REMAINING re-wrap', async () => {
    const c = await setupCommittee();

    // Capture the removed member's wrap count at the instant of the FIRST
    // remaining-member wrap_member (must already be 0 — purge-early, AC-B5).
    let removedWrapsAtFirstRemainingWrap = -1;
    const hooks: TransportHooks = {
      onOp: (op, _n, body) => {
        if (op === 'wrap_member' && String(body.member_user_id) !== ACTOR) {
          if (removedWrapsAtFirstRemainingWrap === -1) {
            removedWrapsAtFirstRemainingWrap = c.srv.wrapsOf(REMOVED).length;
          }
        }
      }
    };
    const { transport, ops } = makeTransport(c.srv, hooks);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    const r = await runRotation(standardOpts(c, client, holder));
    expect(r.status).toBe('ok');

    const iRotate = opIndex(ops, (o) => o.op === 'rotate');
    const iRevoke = opIndex(ops, (o) => o.op === 'revoke_member');
    const iSelfWrap = opIndex(ops, (o) => o.op === 'wrap_member' && o.body.member_user_id === ACTOR);
    const iPopulate = opIndex(ops, (o) => o.op === 'get_all_key_wraps');
    const iFirstRemainingWrap = opIndex(
      ops,
      (o) => o.op === 'wrap_member' && o.body.member_user_id !== ACTOR
    );
    const iFinalize = opIndex(ops, (o) => o.op === 'finalize_rotate');

    expect(iRotate, 'rotate is the first state-mutating RPC').toBe(0);
    expect(iRevoke, 'TM-1/re-pass #21: revoke runs BEFORE any wrap (purge-early)').toBeGreaterThan(
      iRotate
    );
    expect(iRevoke, 'revoke precedes the self-wrap').toBeLessThan(iSelfWrap);
    expect(iSelfWrap, 'the self-wrap is the FIRST wrap').toBeLessThan(iFirstRemainingWrap);
    expect(
      iPopulate,
      're-pass #21(a): the step-5 populate (get_all_key_wraps) runs AFTER the self-wrap'
    ).toBeGreaterThan(iSelfWrap);
    expect(
      iPopulate,
      're-pass #21(a): populate MUST precede any remaining-member re-wrap (so the seal is under the new live key)'
    ).toBeLessThan(iFirstRemainingWrap);
    expect(iFinalize, 'finalize is last').toBe(ops.length - 1);

    expect(
      removedWrapsAtFirstRemainingWrap,
      'AC-B5/TM-1: at the first remaining re-wrap the removed member already has 0 wraps (revoke purged early)'
    ).toBe(0);
  });

  it('AC-B5 (server guard model): wrap_member for the removed INACTIVE member RAISEs rls_denied (:502-503)', async () => {
    // Harness-fidelity check that the migration-0007 active-target gate the
    // composition relies on is modeled. (The authoritative gate is server-side
    // SQL — a pgTAP concern; this pins the CLIENT-observable contract that a
    // re-wrap of an inactive member can never land.)
    const c = await setupCommittee();
    const newKeyId = 'k-epoch-2';
    c.srv.seedEpoch(newKeyId, OLD_EPOCH + 1, null);
    const guard = c.srv.wrapMember(REMOVED, newKeyId, bytesToPgHex(new Uint8Array(48)), 'rot-x');
    expect((guard.body as { ok: boolean }).ok).toBe(false);
    expect((guard.body as { error: string }).error).toBe('rls_denied');
  });
});

// ===========================================================================
// CRASH: TRUE ORPHAN — AC-B7 · TM-4 · re-pass #21, #22
// ===========================================================================
describe('F182-4b orphan crash — AC-B7/TM-4: rotate landed, self-wrap did NOT → typed orphaned', () => {
  it('a self-wrap POST failure yields orphaned, NEVER finalizes a zero-wrap epoch, and never re-generates under new_key_id (F-137)', async () => {
    const c = await setupCommittee();
    // Fail the FIRST wrap_member (the self-wrap) → the new epoch stays zero-wrap.
    const hooks: TransportHooks = {
      override: (op, occurrence) =>
        op === 'wrap_member' && occurrence === 0 ? wireErr('wrap_post_failed', 500) : undefined
    };
    const { transport, ops } = makeTransport(c.srv, hooks);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    const r = await runRotation(standardOpts(c, client, holder));

    expect(r.status, 'AC-B7/TM-4/re-pass #22: a failed self-wrap MUST return orphaned').toBe(
      'orphaned'
    );
    // Never advance to finalize on a zero-wrap epoch.
    expect(
      ops.some((o) => o.op === 'finalize_rotate'),
      're-pass #22: finalize must NOT be called on a zero-wrap orphan epoch'
    ).toBe(false);
    // The orphan epoch has zero wraps and was never re-wrapped with divergent bytes.
    const liveKeyId = c.srv.liveEpoch()!.key_id;
    expect(
      c.srv.wraps.filter((w) => w.key_id === liveKeyId).length,
      'F-137: the orphan key_id is never re-used with different bytes; it stays zero-wrap'
    ).toBe(0);
    // No REMAINING member re-wrap was attempted (the loop never ran).
    expect(ops.some((o) => o.op === 'wrap_member' && o.body.member_user_id !== ACTOR)).toBe(false);
    // The orphaned result carries the rotation context needed to route to abandon.
    expect(JSON.stringify(r)).toContain(liveKeyId);
  });

  it('TM-4/re-pass #21: the orphan abandon path re-drive re-runs revoke (does NOT skip the purge)', async () => {
    const c = await setupCommittee();
    // First run: self-wrap fails → orphaned.
    let failSelfWrap = true;
    const hooks: TransportHooks = {
      override: (op, occurrence) =>
        failSelfWrap && op === 'wrap_member' && occurrence === 0
          ? wireErr('wrap_post_failed', 500)
          : undefined
    };
    const first = makeTransport(c.srv, hooks);
    const client1 = new SupabaseT07Client({ transport: first.transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });
    const r1 = await runRotation(standardOpts(c, client1, holder));
    expect(r1.status, 'first run orphaned').toBe('orphaned');

    // Re-drive (a fresh composition invocation): self-wrap now succeeds.
    failSelfWrap = false;
    const second = makeTransport(c.srv, hooks);
    const client2 = new SupabaseT07Client({ transport: second.transport, localIdentity: c.localIdentity });
    const holder2 = new CommitteeKeyHolder();
    holder2.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });
    const r2 = await runRotation(standardOpts(c, client2, holder2));

    expect(r2.status, 're-drive completes cleanly').toBe('ok');
    // The re-drive minted a FRESH epoch (abandoned the orphan) …
    const reRotate = second.ops.find((o) => o.op === 'rotate');
    expect(reRotate, 're-drive rotates a fresh epoch').toBeDefined();
    // … and re-ran revoke (the purge is NOT skipped on re-drive).
    expect(
      second.ops.some((o) => o.op === 'revoke_member'),
      're-pass #21: the orphan re-drive MUST re-run revoke, never skip the purge'
    ).toBe(true);
  });
});

// ===========================================================================
// CRASH: INCOMPLETE + EXISTING-DATA-READABLE — AC-B4 / AC-B8 · TM-3
// ===========================================================================
describe('F182-4b incomplete crash — AC-B8/TM-3: self-wrap OK, later step fails → incomplete; existing data stays readable', () => {
  it('a finalize failure yields incomplete carrying {rotation_id,new_key_id}; a pre-rotation record still opens (old wrap retained)', async () => {
    const c = await setupCommittee();
    const oldRecord = sealRecord('pre-rotation minutes v1', c.oldKey); // sealed under the OLD key
    // Fail finalize (a benign transport fault, not the R1 epoch-retire case).
    const hooks: TransportHooks = {
      override: (op) => (op === 'finalize_rotate' ? wireErr('unknown', 500) : undefined)
    };
    const { transport, ops } = makeTransport(c.srv, hooks);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    const r = await runRotation(standardOpts(c, client, holder));

    expect(r.status, 'AC-B8/TM-6: a failed finalize must be incomplete, NEVER ok').toBe('incomplete');
    const newKeyId = newKeyIdFrom(ops);
    // Carries the resume context.
    expect(JSON.stringify(r), 'incomplete carries new_key_id for resume').toContain(newKeyId);
    // TM-3: existing data is still readable — the holder retains the old epoch key.
    const opened = await tryReadRecord(holder, oldRecord);
    expect(
      opened,
      'TM-3/AC-B4: a pre-rotation record must still open through the incomplete state (old wrap retained + trial-decrypt)'
    ).toBe('pre-rotation minutes v1');
  });

  it('TM-3/AC-B4: a mid-re-wrap-loop transport failure leaves existing data readable and yields a LOUD non-ok result', async () => {
    const c = await setupCommittee();
    const oldRecord = sealRecord('pre-rotation reprisal v1', c.oldKey);
    // Fail M2's re-wrap (a wrap_member for a non-actor member) mid-loop.
    const hooks: TransportHooks = {
      override: (op, _n, body) =>
        op === 'wrap_member' && String(body.member_user_id) === M2
          ? wireErr('wrap_post_failed', 500)
          : undefined
    };
    const { transport } = makeTransport(c.srv, hooks);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    const r = await runRotation(standardOpts(c, client, holder));

    // Loud + non-ok (either incomplete, or ok_with_pending if the loop treats a
    // hard wrap failure as pending — but NEVER a plain ok, and NEVER a crash).
    expect(
      r.status === 'incomplete' || r.status === 'ok_with_pending',
      `TM-3/AC-B8: a mid-loop wrap failure must be a LOUD non-ok union member, got ${r.status}`
    ).toBe(true);
    expect(r.status, 'never a silent ok on a failed re-wrap').not.toBe('ok');
    // Existing data still readable.
    const opened = await tryReadRecord(holder, oldRecord);
    expect(opened, 'TM-3: pre-rotation data remains openable after a mid-loop failure').toBe(
      'pre-rotation reprisal v1'
    );
  });
});

// ===========================================================================
// RESUMABILITY LIMIT — AC-B6 · TM-5 · re-pass #24
// ===========================================================================
describe('F182-4b resumability — AC-B6/TM-5: only a resumer HOLDING a new-epoch wrap can complete', () => {
  // Build a mid-rotation server state: old(retired) + new(live), rotation started
  // not finalized, resumer's own new-epoch wrap present (or absent).
  async function midRotationServer(opts: {
    resumer: MemberFixture;
    resumerHoldsNewWrap: boolean;
    newKey: Uint8Array;
    newKeyId: string;
  }): Promise<{ srv: FakeKeyServer; localIdentity: BrowserLocalIdentityStore; m1: MemberFixture; m2: MemberFixture }> {
    const srv = new FakeKeyServer();
    srv.seedEpoch(OLD_KEY_ID, OLD_EPOCH, 999); // old epoch retired
    srv.seedEpoch(opts.newKeyId, OLD_EPOCH + 1, null); // new epoch live
    srv.rotations.set('rot-1', {
      rotation_id: 'rot-1',
      new_key_id: opts.newKeyId,
      started: true,
      finalized: false
    });
    const localIdentity = silentStore();
    const m1 = await makeMember(M1, true);
    const m2 = await makeMember(M2, true);
    for (const m of [opts.resumer, m1, m2]) srv.identities.set(m.user_id, m);
    srv.identities.set(REMOVED, await makeMember(REMOVED, false));
    srv.activeMemberCount = 3;
    srv.selfUserId = opts.resumer.user_id;
    await localIdentity.storeIdentityPrivateKey(opts.resumer.user_id, opts.resumer.priv);
    // The resumer's OLD-epoch wrap always exists (they were a member).
    srv.seedWrap(opts.resumer.user_id, OLD_KEY_ID, sodium.crypto_box_seal(new Uint8Array(32), opts.resumer.pub));
    if (opts.resumerHoldsNewWrap) {
      srv.seedWrap(opts.resumer.user_id, opts.newKeyId, sodium.crypto_box_seal(opts.newKey, opts.resumer.pub));
    }
    return { srv, localIdentity, m1, m2 };
  }

  it('AC-B6: a resumer WHO HOLDS a new-epoch wrap completes the re-wrap loop + finalize with a correct count', async () => {
    const resumer = await makeMember(RESUMER_B, true);
    const newKey = sodium.randombytes_buf(sodium.crypto_secretbox_KEYBYTES);
    const newKeyId = 'k-epoch-2';
    const { srv, localIdentity } = await midRotationServer({
      resumer,
      resumerHoldsNewWrap: true,
      newKey,
      newKeyId
    });
    const { transport, ops } = makeTransport(srv);
    const client = new SupabaseT07Client({ transport, localIdentity });
    const holder = new CommitteeKeyHolder(); // fresh session → empty holder

    const r = await runRotation({
      client,
      holder,
      localIdentity,
      user_id: RESUMER_B,
      actor_public_key: resumer.pub,
      removed_member_id: REMOVED,
      remaining_members: [{ user_id: M1 }, { user_id: M2 }],
      resume: { rotation_id: 'rot-1', new_key_id: newKeyId }
    });

    expect(
      r.status === 'ok' || r.status === 'ok_with_pending',
      `AC-B6: a holder-of-new-epoch resumer must complete, got ${r.status}`
    ).toBe(true);
    // resume skips rotate + revoke (they already ran in the crashed initiator).
    expect(ops.some((o) => o.op === 'rotate'), 'resume must NOT re-rotate').toBe(false);
    // M1 + M2 re-wrapped under the new epoch, opening to the new key (forward secrecy).
    expect(srv.wrapOn(M1, newKeyId)).toBeDefined();
    expect(srv.wrapOn(M2, newKeyId)).toBeDefined();
    const fin = ops.find((o) => o.op === 'finalize_rotate');
    expect(fin, 'resume finalizes').toBeDefined();
    expect(fin!.body.members_rewrapped_count, 'count = 1 self + 2 remaining').toBe(3);
  });

  it('AC-B6/TM-5/re-pass #24: a resumer holding NO new-epoch wrap → cannot_resume_not_holder, POSTs ZERO wraps, never seals under an absent key', async () => {
    const resumer = await makeMember(RESUMER_C, true);
    const newKey = sodium.randombytes_buf(sodium.crypto_secretbox_KEYBYTES);
    const newKeyId = 'k-epoch-2';
    const { srv, localIdentity } = await midRotationServer({
      resumer,
      resumerHoldsNewWrap: false, // C never got a new-epoch wrap
      newKey,
      newKeyId
    });
    const sealSpy = vi.spyOn(sodium, 'crypto_box_seal');
    const { transport, ops } = makeTransport(srv);
    const client = new SupabaseT07Client({ transport, localIdentity });
    const holder = new CommitteeKeyHolder();

    const r = await runRotation({
      client,
      holder,
      localIdentity,
      user_id: RESUMER_C,
      actor_public_key: resumer.pub,
      removed_member_id: REMOVED,
      remaining_members: [{ user_id: M1 }, { user_id: M2 }],
      resume: { rotation_id: 'rot-1', new_key_id: newKeyId }
    });

    expect(
      r.status,
      'TM-5/re-pass #24: a resumer with no new-epoch wrap must get cannot_resume_not_holder (populate leaves hasLiveKey()===false)'
    ).toBe('cannot_resume_not_holder');
    expect(holder.hasLiveKey(), 'no live new key was installable for this resumer').toBe(false);
    // Never a seal-under-absent-key: zero wraps POSTed, zero seals of the new key.
    expect(ops.some((o) => o.op === 'wrap_member'), 're-pass #24: POST ZERO wraps').toBe(false);
    expect(sealSpy, 're-pass #24: never seals when hasLiveKey()===false').toHaveBeenCalledTimes(0);
    expect(ops.some((o) => o.op === 'finalize_rotate'), 'never finalizes an un-completable resume').toBe(
      false
    );
  });

  it('RE-REVIEW C / adversarial Finding 1: a resumer with server-side wraps but NO local privkey → failed/needs_recovery (restore-from-recovery), NOT cannot_resume_not_holder', async () => {
    // Distinct from re-pass #24: THAT resumer HAS a privkey (opens their old
    // wrap) but holds no NEW-epoch wrap → cannot_resume_not_holder is correct.
    // HERE the resumer is on a new/unrestored device with NO local identity
    // privkey. `getAllCommitteeKeyWrapsForSelf` still returns a non-empty SETOF
    // (their OLD-epoch wrap exists server-side, seeded by midRotationServer), so
    // `unwrapAllCommitteeKeysViaProduction` reaches `getIdentityPrivateKey` →
    // throws → `needs_recovery`. The resume arm must surface that HONESTLY
    // (route to restore-from-recovery, ADR-0026 AC-7) and NOT collapse it to
    // `cannot_resume_not_holder` — whose "abandon + re-drive" guidance itself
    // requires opening a wrap and is equally impossible without recovery, so the
    // actionable signal would be lost. Mirrors the fresh-path step-1
    // `needs_recovery` handling (production-flows.ts:1111-1113).
    const resumer = await makeMember(RESUMER_D, true);
    const newKey = sodium.randombytes_buf(sodium.crypto_secretbox_KEYBYTES);
    const newKeyId = 'k-epoch-2';
    // Server state carries the resumer's OLD-epoch wrap (non-empty SETOF) but we
    // deliberately DISCARD midRotationServer's privkey-bearing store and drive
    // the ceremony with a FRESH, empty store → no local privkey for RESUMER_D.
    const { srv } = await midRotationServer({
      resumer,
      resumerHoldsNewWrap: false,
      newKey,
      newKeyId
    });
    const noPrivStore = silentStore(); // new/unrestored device — never stored a privkey
    const sealSpy = vi.spyOn(sodium, 'crypto_box_seal');
    const { transport, ops } = makeTransport(srv);
    const client = new SupabaseT07Client({ transport, localIdentity: noPrivStore });
    const holder = new CommitteeKeyHolder();

    const r = await runRotation({
      client,
      holder,
      localIdentity: noPrivStore,
      user_id: RESUMER_D,
      actor_public_key: resumer.pub,
      removed_member_id: REMOVED,
      remaining_members: [{ user_id: M1 }, { user_id: M2 }],
      resume: { rotation_id: 'rot-1', new_key_id: newKeyId }
    });

    expect(
      r.status,
      'adversarial Finding 1: a no-privkey resumer holding server-side wraps must surface needs_recovery, not cannot_resume_not_holder'
    ).toBe('failed');
    expect(
      (r as { reason?: string }).reason,
      'the honest restore-from-recovery signal must reach the caller (ADR-0026 AC-7)'
    ).toBe('needs_recovery');
    // Fail-closed: no live key installed, ZERO wraps POSTed, ZERO seals, never finalizes.
    expect(holder.hasLiveKey(), 'no live new key installed on a recovery-needed device').toBe(false);
    expect(ops.some((o) => o.op === 'wrap_member'), 'POST ZERO wraps on a needs_recovery resume').toBe(
      false
    );
    expect(sealSpy, 'never seals when the device cannot open its own wraps').toHaveBeenCalledTimes(0);
    expect(ops.some((o) => o.op === 'finalize_rotate'), 'never finalizes a needs_recovery resume').toBe(
      false
    );
  });
});

// ===========================================================================
// FAIL-LOUD UNION — AC-B8 · TM-6 · re-pass #22
// ===========================================================================
describe('F182-4b fail-loud — AC-B8/TM-6/re-pass #22: never ok without BOTH self-wrap AND finalize', () => {
  it('a self-wrap failure is orphaned (never ok, never finalize); a finalize failure is incomplete (never ok) — no silent dead key', async () => {
    // Case 1 — self-wrap fails → orphaned, no finalize.
    {
      const c = await setupCommittee();
      const hooks: TransportHooks = {
        override: (op, occurrence) =>
          op === 'wrap_member' && occurrence === 0 ? wireErr('wrap_post_failed', 500) : undefined
      };
      const { transport, ops } = makeTransport(c.srv, hooks);
      const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
      const holder = new CommitteeKeyHolder();
      holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });
      const r = await runRotation(standardOpts(c, client, holder));
      expect(r.status, 're-pass #22: no self-wrap ⇒ orphaned, never ok').toBe('orphaned');
      expect(r.status).not.toBe('ok');
      expect(ops.some((o) => o.op === 'finalize_rotate'), 'no finalize on a zero-wrap epoch').toBe(
        false
      );
    }
    // Case 2 — finalize fails → incomplete, never ok.
    {
      const c = await setupCommittee();
      const hooks: TransportHooks = {
        override: (op) => (op === 'finalize_rotate' ? wireErr('unknown', 500) : undefined)
      };
      const { transport } = makeTransport(c.srv, hooks);
      const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
      const holder = new CommitteeKeyHolder();
      holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });
      const r = await runRotation(standardOpts(c, client, holder));
      expect(r.status, 're-pass #22: a failed finalize ⇒ incomplete, never ok').toBe('incomplete');
      expect(r.status).not.toBe('ok');
    }
  });
});

// ===========================================================================
// MERGED-GUARD ENVELOPE — AC-B10 · TM-8 · F-VAL-1(b) latch + F-196 zeroize + F-195
// ===========================================================================
describe('F182-4b merged-guard — AC-B10/TM-8: session-end wipe during a fetch fails closed (no resurrection), zeroizes in-flight buffers', () => {
  it('a wipe during the STEP-1 precondition unwrap fetch → fail closed BEFORE rotate; holder empty; in-flight buffer zeroized (F-196); nothing POSTed', async () => {
    const c = await setupCommittee();
    // Empty holder → the composition runs the step-1 latch-guarded unwrap.
    const holder = new CommitteeKeyHolder();
    expect(holder.hasLiveKey()).toBe(false);

    const sealOpenSpy = vi.spyOn(sodium, 'crypto_box_seal_open');
    const hooks: TransportHooks = {
      // Fire a session-end wipe WHILE the step-1 get_key_wrap fetch is in flight
      // — strictly before the composition's holder.set() install (deterministic;
      // no timers). Advances wipeGeneration even on an empty holder.
      onOp: (op) => {
        if (op === 'get_key_wrap') holder.onSessionRevoked();
      }
    };
    const { transport, ops } = makeTransport(c.srv, hooks);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });

    const r = await runRotation(standardOpts(c, client, holder));

    // Fail closed BEFORE any state-mutating RPC (the precondition is pre-rotate).
    expect(ops.some((o) => o.op === 'rotate'), 'AC-B10: no rotate after a step-1 wipe').toBe(false);
    expect(ops.some((o) => o.op === 'wrap_member'), 'no wrap POSTed after a step-1 wipe').toBe(false);
    expect(r.status, 'a step-1 session-end wipe fails the composition closed').toBe('failed');
    // Holder NOT resurrected.
    expect(holder.hasLiveKey(), 'F-VAL-1(b): the holder must not be resurrected').toBe(false);
    expect(holder.isPopulated()).toBe(false);
    // F-196: every buffer the fetch handed back is zeroized on the latch-abandon.
    const opened = sealOpenSpy.mock.results.filter(
      (res) => res.type === 'return' && res.value instanceof Uint8Array
    );
    expect(opened.length, 'the step-1 unwrap opened at least one buffer').toBeGreaterThanOrEqual(1);
    for (const res of opened) {
      expect(
        isAllZero(res.value as Uint8Array),
        'F-196/TM-8: an in-flight decrypted buffer was NOT zeroized on the latch-abandon'
      ).toBe(true);
    }
  });

  it('a wipe during the STEP-5 install fetch → no populate (holder stays wiped), no re-wrap POST after the wipe, in-flight buffers zeroized (F-196)', async () => {
    const c = await setupCommittee();
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH }); // step 1 skipped

    const sealOpenSpy = vi.spyOn(sodium, 'crypto_box_seal_open');
    const hooks: TransportHooks = {
      // Fire the session-end wipe WHILE the step-5 get_all_key_wraps fetch is in
      // flight — after rotate/revoke/self-wrap, before the populate install.
      onOp: (op) => {
        if (op === 'get_all_key_wraps') holder.onPanicWipe();
      }
    };
    const { transport, ops } = makeTransport(c.srv, hooks);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });

    const r = await runRotation(standardOpts(c, client, holder));

    // Loud, fail-closed (never ok / ok_with_pending — a wipe cannot be a success).
    expect(
      r.status !== 'ok' && r.status !== 'ok_with_pending',
      `AC-B10: a step-5 session-end wipe must fail closed, got ${r.status}`
    ).toBe(true);
    // Holder NOT resurrected with the new epoch (populate abandoned).
    expect(holder.hasLiveKey(), 'F-VAL-1(b): populate must not resurrect after the wipe').toBe(false);
    // Exactly the self-wrap POSTed (before the wipe); NO remaining-member re-wrap after.
    const iAllWraps = opIndex(ops, (o) => o.op === 'get_all_key_wraps');
    const wrapsAfterWipe = ops
      .map((o, i) => ({ o, i }))
      .filter(({ o, i }) => o.op === 'wrap_member' && i > iAllWraps);
    expect(
      wrapsAfterWipe.length,
      'AC-B10: NO ciphertext may be POSTed after a session-end wipe'
    ).toBe(0);
    // F-196: the step-5 unwrapAll buffers are zeroized on the latch-abandon.
    const opened = sealOpenSpy.mock.results.filter(
      (res) => res.type === 'return' && res.value instanceof Uint8Array
    );
    expect(opened.length, 'step-5 unwrapAll opened at least one buffer').toBeGreaterThanOrEqual(1);
    for (const res of opened) {
      expect(
        isAllZero(res.value as Uint8Array),
        'F-196/TM-8: a step-5 in-flight decrypted buffer was NOT zeroized on the latch-abandon'
      ).toBe(true);
    }
  });
});

// ===========================================================================
// CONCURRENCY — AC-B12 · TM-13 · R1
// ===========================================================================
describe('F182-4b concurrency — AC-B12/TM-13/R1: a competing rotation fails the loser LOUD, no data loss', () => {
  it('AC-B12: rotate returns rotation_in_progress (55P03) → typed retry/resume, no crash, no second epoch minted, no finalize', async () => {
    const c = await setupCommittee();
    const hooks: TransportHooks = {
      override: (op) => (op === 'rotate' ? wireErr('rotation_in_progress', 409) : undefined)
    };
    const { transport, ops } = makeTransport(c.srv, hooks);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    const r = await runRotation(standardOpts(c, client, holder));

    expect(r.status, 'AC-B12: rotation_in_progress must not crash; it is a typed non-ok').not.toBe(
      'ok'
    );
    expect(
      JSON.stringify(r),
      'AC-B12: the loser surfaces a typed rotation_in_progress retry/resume signal'
    ).toContain('rotation_in_progress');
    // The loser mints no epoch (the override short-circuited srv.rotate).
    expect(c.srv.epochs.length, 'no second epoch minted by the loser').toBe(1);
    expect(ops.some((o) => o.op === 'finalize_rotate')).toBe(false);
    expect(ops.some((o) => o.op === 'wrap_member')).toBe(false);
  });

  it('R1/TM-13: a second rotation retiring the first`s epoch during its client tail → finalize fails LOUD (invalid_new_key), result incomplete, no wrong-key ciphertext, data readable', async () => {
    const c = await setupCommittee();
    const oldRecord = sealRecord('pre-rotation minutes R1', c.oldKey);
    // Just before the first ceremony's finalize, a concurrent rotation retires
    // its new epoch (the tail-window R1 case the advisory lock cannot cover).
    const hooks: TransportHooks = {
      onOp: (op, occurrence) => {
        if (op === 'finalize_rotate' && occurrence === 0) c.srv.concurrentRotate();
      }
    };
    const { transport, ops } = makeTransport(c.srv, hooks);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    const r = await runRotation(standardOpts(c, client, holder));

    // Finalize was attempted and the server rejected it (invalid_new_key).
    const fin = ops.find((o) => o.op === 'finalize_rotate');
    expect(fin, 'R1: the ceremony reaches finalize').toBeDefined();
    expect(
      r.status,
      'R1/TM-13: a finalize rejected because the epoch was retired mid-tail must be a LOUD incomplete, never ok'
    ).toBe('incomplete');
    // No wrong-key ciphertext: the member wraps POSTed before the tail-rotate open
    // to the (correct) new key, not garbage.
    const newKeyId = newKeyIdFrom(ops);
    const newKey = recoverNewKey(c.srv, c.actor, newKeyId);
    const m1Wrap = c.srv.wrapOn(M1, newKeyId);
    if (m1Wrap) {
      const opened = sodium.crypto_box_seal_open(m1Wrap.sealed, c.m1.pub, c.m1.priv);
      expect(Array.from(opened), 'R1: no wrong-key ciphertext — M1`s wrap holds the real new key').toEqual(
        Array.from(newKey)
      );
    }
    // Existing data stays readable (no data loss).
    const opened = await tryReadRecord(holder, oldRecord);
    expect(opened, 'R1: existing data stays readable through the loud failure').toBe(
      'pre-rotation minutes R1'
    );
  });
});

// ===========================================================================
// ≥1-ACTIVE-MEMBER GUARD (server) — rotate refuses when < 1 active member
// ===========================================================================
describe('F182-4b active-member guard — rotate surfaces no_active_members typed failure', () => {
  it('when the committee has < 1 active member, rotate refuses; the composition returns failed/no_active_members and mints no epoch', async () => {
    const c = await setupCommittee();
    c.srv.activeMemberCount = 0; // the :583-585 guard trips
    const { transport, ops } = makeTransport(c.srv);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    const r = await runRotation(standardOpts(c, client, holder));

    expect(r.status, 'a no_active_members rotate is a typed failure, not a crash').toBe('failed');
    expect(
      JSON.stringify(r),
      'the failure names no_active_members so the caller can surface the right copy'
    ).toContain('no_active_members');
    // No epoch minted, no revoke, no wrap.
    expect(c.srv.epochs.length).toBe(1);
    expect(ops.some((o) => o.op === 'revoke_member')).toBe(false);
    expect(ops.some((o) => o.op === 'wrap_member')).toBe(false);
  });
});

// ===========================================================================
// OFFLINE / UNENROLLED EDGE — AC-B11 · TM-12
// ===========================================================================
describe('F182-4b offline edge — AC-B11/TM-12: a member_not_enrolled remaining member is skipped into pending, not an error', () => {
  it('M2 reporting member_not_enrolled → ok_with_pending (M2 in pending_members), finalize count reduced, M2 keeps pre-rotation reads', async () => {
    const c = await setupCommittee();
    // M2's disclosure reports not-enrolled → SKIP.
    const hooks: TransportHooks = {
      override: (op, _n, body) =>
        op === 'get_member_pubkey' && String(body.target_user_id) === M2
          ? wireErr('member_not_enrolled', 403)
          : undefined
    };
    const { transport, ops } = makeTransport(c.srv, hooks);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    const r = await runRotation(standardOpts(c, client, holder));

    expect(r.status, 'AC-B11: a skipped member is ok_with_pending, NOT an error').toBe(
      'ok_with_pending'
    );
    expect(
      JSON.stringify((r as { pending_members?: unknown }).pending_members ?? r),
      'AC-B11: the skipped member lands in pending_members'
    ).toContain(M2);
    const newKeyId = newKeyIdFrom(ops);
    // M1 re-wrapped; M2 skipped (no new-epoch wrap).
    expect(c.srv.wrapOn(M1, newKeyId)).toBeDefined();
    expect(c.srv.wrapOn(M2, newKeyId), 'the skipped member gets no new-epoch wrap').toBeUndefined();
    // finalize still runs with the reduced count = 1 self + 1 (M1) = 2.
    const fin = ops.find((o) => o.op === 'finalize_rotate');
    expect(fin, 'finalize still runs with the reduced count').toBeDefined();
    expect(fin!.body.members_rewrapped_count, 'AC-B11: count = 1 self + 1 re-wrapped (M2 skipped)').toBe(2);
    // M2 still opens pre-rotation data (its OLD-epoch wrap is retained, not purged).
    expect(
      c.srv.wrapOn(M2, OLD_KEY_ID),
      'AC-B11: the skipped member keeps its old-epoch wrap → still opens pre-rotation data'
    ).toBeDefined();
  });
});

// ===========================================================================
// ZEROIZE + NEVER-LOG — AC-B9 · TM-10 · re-pass #25
// ===========================================================================
describe('F182-4b zeroize/no-log — AC-B9/TM-10/re-pass #25: newKey zeroized on every exit; no key material logged', () => {
  it('the generated plaintext new key is .fill(0) on the ok exit', async () => {
    const c = await setupCommittee();
    const rbSpy = vi.spyOn(sodium, 'randombytes_buf');
    const { transport } = makeTransport(c.srv);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    const r = await runRotation(standardOpts(c, client, holder));
    expect(r.status).toBe('ok');

    // The composition generated a 32-byte data key; it must be zeroized post-exit.
    const keyBufs = rbSpy.mock.results
      .filter((res) => res.type === 'return' && res.value instanceof Uint8Array)
      .map((res) => res.value as Uint8Array)
      .filter((b) => b.length === sodium.crypto_secretbox_KEYBYTES);
    expect(keyBufs.length, 'the composition generated a fresh 32-byte new key').toBeGreaterThanOrEqual(
      1
    );
    for (const b of keyBufs) {
      expect(
        isAllZero(b),
        'AC-B9/re-pass #25: the plaintext newKey buffer must be .fill(0) on the ok exit'
      ).toBe(true);
    }
  });

  it('the generated new key is .fill(0) even on the orphaned exit (re-pass #25 — every union exit zeroizes)', async () => {
    const c = await setupCommittee();
    const rbSpy = vi.spyOn(sodium, 'randombytes_buf');
    const hooks: TransportHooks = {
      override: (op, occurrence) =>
        op === 'wrap_member' && occurrence === 0 ? wireErr('wrap_post_failed', 500) : undefined
    };
    const { transport } = makeTransport(c.srv, hooks);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    const r = await runRotation(standardOpts(c, client, holder));
    expect(r.status).toBe('orphaned');

    const keyBufs = rbSpy.mock.results
      .filter((res) => res.type === 'return' && res.value instanceof Uint8Array)
      .map((res) => res.value as Uint8Array)
      .filter((b) => b.length === sodium.crypto_secretbox_KEYBYTES);
    expect(keyBufs.length, 'the newKey was generated at step 4 before the self-wrap POST').toBeGreaterThanOrEqual(
      1
    );
    for (const b of keyBufs) {
      expect(
        isAllZero(b),
        're-pass #25: the newKey buffer must be .fill(0) even when the composition returns orphaned'
      ).toBe(true);
    }
  });

  it('TM-10/AC-B9: no key material (new key, old key, actor/member privkeys) appears in console or the structured log across the full rotation', async () => {
    const c = await setupCommittee();
    const logs: string[] = [];
    for (const m of ['log', 'warn', 'error', 'info', 'debug'] as const) {
      vi.spyOn(console, m).mockImplementation((...a: unknown[]) => {
        logs.push(a.map(String).join(' '));
      });
    }
    const oldKeyHex = sodium.to_hex(c.oldKey);
    const actorPrivHex = sodium.to_hex(c.actor.priv);

    const { transport, ops } = makeTransport(c.srv);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    const r = await runRotation(standardOpts(c, client, holder));
    expect(r.status).toBe('ok');

    // Recover the new key (from the server self-wrap) to search the logs for it.
    const newKeyId = newKeyIdFrom(ops);
    const newKeyHex = sodium.to_hex(recoverNewKey(c.srv, c.actor, newKeyId));

    const haystacks: string[] = [
      ...logs,
      ...__getCapturedLines().map((l) => JSON.stringify(l)),
      JSON.stringify(r)
    ];
    for (const h of haystacks) {
      expect(h, 'TM-10: the new committee key must never be logged').not.toContain(newKeyHex);
      expect(h, 'TM-10: the old committee key must never be logged').not.toContain(oldKeyHex);
      expect(h, 'TM-10: the actor identity privkey must never be logged').not.toContain(actorPrivHex);
      expect(h, 'TM-10: the member privkeys must never be logged').not.toContain(
        sodium.to_hex(c.m1.priv)
      );
      expect(h).not.toContain(sodium.to_hex(c.m2.priv));
    }
  });
});

// ===========================================================================
// NO SEAL-PATH ESCALATION — AC-B13 · TM-9 · re-pass #15 carry
// ===========================================================================
describe('F182-4b no-escalation — AC-B13/TM-9: get_all_key_wraps fires ONLY at the deliberate step-5 install', () => {
  it('across the whole composition, get_all_key_wraps is dispatched exactly once (the re-wrap seals never escalateToAllEpochs)', async () => {
    const c = await setupCommittee();
    const { transport, ops } = makeTransport(c.srv);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    const r = await runRotation(standardOpts(c, client, holder));
    expect(r.status).toBe('ok');

    expect(
      ops.filter((o) => o.op === 'get_all_key_wraps').length,
      'AC-B13/TM-9: get_all_key_wraps must fire exactly once (step-5 install only); the re-wrap seals must NOT escalate'
    ).toBe(1);
  });
});

// ===========================================================================
// FAN-OUT + SELF-DETECT — TM-11 · F-188 · R2
// ===========================================================================
describe('F182-4b fan-out/self-detect — TM-11/R2: one disclosure per member; a substituted pubkey self-detects', () => {
  it('exactly one get_member_pubkey per remaining member (no double-disclosure TOCTOU)', async () => {
    const c = await setupCommittee();
    const { transport, ops } = makeTransport(c.srv);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    const r = await runRotation(standardOpts(c, client, holder));
    expect(r.status).toBe('ok');

    const disclosures = ops.filter((o) => o.op === 'get_member_pubkey');
    expect(disclosures.length, 'TM-11: (N-1) disclosures — one per remaining member, none for self').toBe(
      2
    );
    const targets = disclosures.map((o) => String(o.body.target_user_id)).sort();
    expect(targets, 'each remaining member disclosed exactly once').toEqual([M1, M2].sort());
  });

  it('R2 self-detect: a server-substituted (coherent) pubkey for M2 is sealed, but M2`s real privkey fails to open it — pending-grant self-detect holds', async () => {
    const c = await setupCommittee();
    // A coherent {pubkey, fingerprint} pair for a DIFFERENT keypair — the machine-
    // only self-consistency assert passes (both fields come from the server), but
    // the LEGITIMATE M2 cannot open a wrap sealed to the substitute.
    const substitute = sodium.crypto_box_keypair();
    const subFingerprint = await pubkeyFingerprint(substitute.publicKey);
    c.srv.substitutePubkey.set(M2, { pub: substitute.publicKey, fingerprint: subFingerprint });

    const { transport, ops } = makeTransport(c.srv);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    const r = await runRotation(standardOpts(c, client, holder));
    // The client cannot detect a coherent server substitution (honest R2 limit) —
    // the composition still completes.
    expect(
      r.status === 'ok' || r.status === 'ok_with_pending',
      'R2: a coherent server substitution is not client-detectable; the composition completes'
    ).toBe(true);

    const newKeyId = newKeyIdFrom(ops);
    const m2Wrap = c.srv.wrapOn(M2, newKeyId);
    expect(m2Wrap, 'a wrap for M2 was POSTed (to the substituted pubkey)').toBeDefined();
    // Self-detect: M2's REAL privkey cannot open the substituted-pubkey wrap.
    let opened: Uint8Array | null = null;
    try {
      opened = sodium.crypto_box_seal_open(m2Wrap!.sealed, c.m2.pub, c.m2.priv);
    } catch {
      opened = null;
    }
    expect(
      opened,
      'TM-11/R2: the legitimate M2 cannot open a wrap sealed to a substituted pubkey → self-detect (pending-grant), never a silent wrong-key'
    ).toBeNull();
    // The un-substituted M1 opens its wrap normally (to the real new key).
    const m1Wrap = c.srv.wrapOn(M1, newKeyId)!;
    const m1Opened = sodium.crypto_box_seal_open(m1Wrap.sealed, c.m1.pub, c.m1.priv);
    expect(m1Opened.length, 'M1 (un-substituted) opens to the real 32-byte new key').toBe(32);
  });
});

// ===========================================================================
// R3 FAIL-SAFE — TM-7 fail-closed variant · R3: step-5 all-wraps omits new_key_id
// ---------------------------------------------------------------------------
// REQUIRED invariant (both R3-acceptable implementations satisfy it): on a
// step-5 all-wraps response that OMITS the just-minted new_key_id, the
// composition must be fail-SAFE — it either self-heals to the CORRECT new key
// (via the still-honest single-live probe) OR fails LOUD, but NEVER a silent
// success that seals remaining members under the WRONG (retired) epoch. The
// LOUD typed "contains-new_key_id-as-live" diagnostic is the RECOMMENDED (R3)
// hardening; "never a wrong-epoch wrap / a success must be genuine" is REQUIRED.
// ===========================================================================
describe('F182-4b R3 fail-safe — TM-7: a step-5 all-wraps dropping new_key_id never yields a wrong-epoch wrap / silent-wrong-key success', () => {
  it('when step-5 all-wraps omits new_key_id, no remaining member is sealed under the retired old epoch and any ok is a GENUINE new-key success', async () => {
    const c = await setupCommittee();
    // Only get_all_key_wraps lies (drops the new epoch); committee_key_state and
    // get_key_wrap stay honest — the realistic F-192 inconsistency. A retired-only
    // populate must NOT let the re-wrap loop seal under the old epoch.
    const hooks: TransportHooks = {
      override: (op) => {
        if (op !== 'get_all_key_wraps') return undefined;
        const oldWrap = c.srv.wrapOn(ACTOR, OLD_KEY_ID)!;
        return wireOk([
          {
            key_id: OLD_KEY_ID,
            epoch: OLD_EPOCH,
            wrapped_ciphertext_hex: bytesToPgHex(oldWrap.sealed),
            is_live: false // new_key_id omitted — no live row in the returned set
          }
        ]);
      }
    };
    const { transport, ops } = makeTransport(c.srv, hooks);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    const r = await runRotation(standardOpts(c, client, holder));

    const newKeyId = c.srv.liveEpoch()!.key_id;
    const newKey = recoverNewKey(c.srv, c.actor, newKeyId);

    // REQUIRED #1 — NO remaining-member re-wrap under the retired old epoch.
    const remainingWraps = ops.filter(
      (o) => o.op === 'wrap_member' && o.body.member_user_id !== ACTOR
    );
    for (const w of remainingWraps) {
      expect(
        w.body.key_id,
        'R3/TM-7 (REQUIRED): a re-wrap must never be POSTed under the retired old epoch — ' +
          'a dropped-new-key step-5 response must self-heal to the live new epoch or fail loud, never seal under old'
      ).toBe(newKeyId);
    }
    // REQUIRED #2 — the holder never designates the RETIRED epoch as its sealing key.
    expect(
      holder.getKeyId() === OLD_KEY_ID,
      'R3: the holder must never seal under the retired old epoch after a dropped-new-key step-5 response'
    ).toBe(false);
    // REQUIRED #3 — any success must be GENUINE: if the composition returns ok /
    // ok_with_pending, every re-wrapped member opens to the REAL new key (never a
    // silent wrong-key "success"). A LOUD non-ok is equally acceptable (R3 fail-closed).
    if (r.status === 'ok' || r.status === 'ok_with_pending') {
      for (const m of [c.m1, c.m2]) {
        const w = c.srv.wrapOn(m.user_id, newKeyId);
        if (!w) continue; // a member skipped into pending is allowed
        const opened = sodium.crypto_box_seal_open(w.sealed, m.pub, m.priv);
        expect(
          Array.from(opened),
          'R3/TM-7: a reported success must be genuine — the member`s wrap opens to the real new key, never a silent wrong-key'
        ).toEqual(Array.from(newKey));
      }
    }
  });
});

// ===========================================================================
// ADVERSARIAL REVIEW — RED-FIRST regression pins (F182-4b composition).
// ---------------------------------------------------------------------------
// Three defects the adversarial review found in `rotateCommitteeKeyOnRemoval
// ViaProduction`. Each test is RED against the CURRENT implementation and is
// the GREEN target the fix must satisfy. Determinism: every fault (wipe / RPC
// error / malformed input) is injected via the transport/holder hooks, never a
// timer (honoring the F-190 lesson: deterministic injection, never wall-clock).
// ===========================================================================
describe('F182-4b adversarial review — RED-first regression pins', () => {
  // -------------------------------------------------------------------------
  // FINDING 1 (HIGH) — mid-ceremony panic-wipe resurrection with ciphertext
  // egress. The step-5 install re-checks a FRESH `installGen` snapshotted AFTER
  // steps 2-4 (production-flows.ts:1170) instead of the composition-entry
  // `entryGen` (:1077). A session-end wipe landing DURING a steps-2-4 await
  // advances `wipeGeneration` before `installGen` is read → the wipe is absorbed
  // into the step-5 baseline → the :1185 re-check passes → `populate()`
  // RESURRECTS the wiped holder → the re-wrap loop seals + POSTs `wrap_member`
  // off-device AFTER the wipe → returns `ok`.
  //
  // The wipe is injected on the FIRST `wrap_member` op (= the step-4 actor
  // self-wrap), i.e. strictly BEFORE the step-5 `installGen` snapshot at :1170.
  // -------------------------------------------------------------------------
  it('FINDING 1 (HIGH): a session-end wipe DURING the steps-2-4 self-wrap await must not be absorbed into the step-5 latch — no resurrection, no post-wipe ciphertext egress, loud non-ok, no finalize', async () => {
    const c = await setupCommittee();
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH }); // step 1 skipped

    let wipeCalls = 0;
    let wipeCallsAtSelfWrap = -1; // proves the wipe landed at step-4, before step-5 populate
    const hooks: TransportHooks = {
      onOp: (op, occurrence) => {
        // Fire the session-end wipe WHILE the step-4 self-wrap POST is in flight
        // (the FIRST wrap_member op). This advances wipeGeneration BEFORE the
        // composition snapshots installGen at step 5 (production-flows.ts:1170) —
        // the exact race the fresh installGen baseline fails to detect.
        if (op === 'wrap_member' && occurrence === 0) {
          holder.onPanicWipe();
          wipeCalls += 1;
          wipeCallsAtSelfWrap = wipeCalls;
        }
      }
    };
    const { transport, ops } = makeTransport(c.srv, hooks);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });

    const r = await runRotation(standardOpts(c, client, holder));

    // Determinism guard — the wipe was injected exactly once, at step-4 (the
    // self-wrap), which is strictly before the step-5 populate install.
    expect(
      wipeCallsAtSelfWrap,
      'determinism: the session-end wipe must have landed mid-ceremony (at the step-4 self-wrap), before the step-5 populate'
    ).toBe(1);
    expect(wipeCalls, 'determinism: exactly one wipe was injected during the ceremony').toBe(1);

    // (a) The wiped holder must NOT be resurrected by the step-5 populate.
    expect(
      holder.hasLiveKey(),
      'FINDING 1(a): a holder wiped mid-ceremony must NOT be resurrected with a live key by the step-5 populate'
    ).toBe(false);
    expect(
      holder.isPopulated(),
      'FINDING 1(a): the just-wiped key map must NOT be repopulated after a mid-ceremony session-end wipe'
    ).toBe(false);

    // (b) NO ciphertext sealed + POSTed off-device after the wipe: the remaining-
    // member re-wrap loop must never fire (only the in-flight self-wrap that the
    // wipe landed on was recorded).
    const remainingWraps = ops.filter(
      (o) => o.op === 'wrap_member' && String(o.body.member_user_id) !== ACTOR
    );
    expect(
      remainingWraps.length,
      'FINDING 1(b): no remaining-member ciphertext may be sealed + POSTed off-device after a session-end wipe (the wiped key resurrected and egressed)'
    ).toBe(0);

    // (c) A LOUD non-ok result — a wipe can never be a success. The step-5 latch-
    // abandon for the fresh (non-resume) path is `incomplete` (resumable): the
    // self-wrap landed, so a re-authenticated actor holding the new-epoch wrap can
    // complete it.
    expect(
      r.status,
      'FINDING 1(c): a mid-ceremony session-end wipe must fail LOUD as incomplete, never a silent ok'
    ).toBe('incomplete');
    expect(r.status, 'FINDING 1(c): never ok on a wiped ceremony').not.toBe('ok');
    expect(r.status, 'FINDING 1(c): never ok_with_pending on a wiped ceremony').not.toBe(
      'ok_with_pending'
    );

    // (d) finalize must never run on a wiped ceremony.
    expect(
      ops.some((o) => o.op === 'finalize_rotate'),
      'FINDING 1(d): finalize must NOT be called after a mid-ceremony session-end wipe'
    ).toBe(false);
  });

  // -------------------------------------------------------------------------
  // RE-REVIEW FINDING A (HIGH) — step-6 re-wrap-LOOP resurrection with ciphertext
  // egress. The SAME resurrection/egress class as Finding 1 (already fixed at the
  // step-5 install by re-checking the composition-ENTRY `entryGen` :1087/:1221),
  // surviving one step LATER inside the re-wrap loop.
  //
  // After step 5 installs the new epoch live (`holder.populate`), a session-end
  // wipe landing during the loop's `getMemberPubkey` await (production-flows.ts
  // :1259) empties the holder (hasLiveKey()===false, wipeGeneration ticks). The
  // composition does NOT re-check `entryGen` inside the loop, so it proceeds to
  // `wrapMemberInViaProduction` (:1275) with a wiped holder → that helper takes
  // its OWN empty-holder re-fetch branch (:762). But that branch's internal latch
  // snapshots a POST-wipe baseline (`const gen = holder.wipeGeneration()` :769),
  // so its :791 re-check cannot see the EARLIER wipe → `holder.set()` (:794)
  // RESURRECTS the just-wiped holder → it seals + POSTs a member wrap off-device
  // AFTER the wipe → returns ok → the loop continues, finalizes, and the whole
  // ceremony returns `ok`. Post-wipe ciphertext egress + a clean `ok` on a wiped
  // session.
  //
  // The wipe is injected on the FIRST `get_member_pubkey` op (occurrence 0) — the
  // step-6 loop's first disclosure, strictly AFTER the step-5 populate and BEFORE
  // any remaining-member re-wrap. Deterministic (transport/holder hook, no timer).
  // -------------------------------------------------------------------------
  it('RE-REVIEW A (HIGH): a session-end wipe during the step-6 loop`s getMemberPubkey await must not be resurrected by wrapMemberInViaProduction`s empty-holder re-fetch — no resurrection, no post-wipe ciphertext egress, incomplete, no finalize', async () => {
    const c = await setupCommittee();
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH }); // step 1 skipped

    let wipeCalls = 0;
    let hadLiveKeyAtWipe = false;
    let liveKeyIdAtWipe: string | null = null;
    let remainingWrapsBeforeWipe = -1;
    let remainingWrapCount = 0;
    const hooks: TransportHooks = {
      onOp: (op, occurrence, body) => {
        // Count remaining-member (non-self) re-wraps as they are dispatched.
        if (op === 'wrap_member' && String(body.member_user_id) !== ACTOR) {
          remainingWrapCount += 1;
        }
        // Fire the session-end wipe WHILE the FIRST remaining-member disclosure
        // (get_member_pubkey occurrence 0) is in flight — i.e. mid step-6 loop,
        // AFTER the step-5 populate installed the new epoch live, BEFORE any
        // remaining re-wrap. This advances wipeGeneration; the composition's
        // entryGen latch is not re-checked in the loop, and the empty-holder
        // re-fetch inside wrapMemberInViaProduction snapshots a POST-wipe baseline
        // so it cannot detect this earlier wipe (production-flows.ts:769/:791).
        if (op === 'get_member_pubkey' && occurrence === 0) {
          hadLiveKeyAtWipe = holder.hasLiveKey();
          liveKeyIdAtWipe = holder.getKeyId();
          remainingWrapsBeforeWipe = remainingWrapCount;
          holder.onPanicWipe();
          wipeCalls += 1;
        }
      }
    };
    const { transport, ops } = makeTransport(c.srv, hooks);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });

    const r = await runRotation(standardOpts(c, client, holder));

    // Determinism guard — the wipe landed exactly once, AFTER the step-5 populate
    // (the holder was live under the NEW epoch, not the initial old-epoch set())
    // and BEFORE any remaining-member re-wrap.
    expect(wipeCalls, 'determinism: exactly one wipe was injected during the step-6 loop').toBe(1);
    expect(
      hadLiveKeyAtWipe,
      'determinism: the step-5 populate installed a live key before the wipe (the wipe is post-populate)'
    ).toBe(true);
    expect(
      liveKeyIdAtWipe,
      'determinism: the live key at the wipe is the NEW epoch — proving the wipe landed AFTER the step-5 populate, not on the initial old-epoch set()'
    ).toBe(newKeyIdFrom(ops));
    expect(
      remainingWrapsBeforeWipe,
      'determinism: the wipe landed BEFORE any remaining-member re-wrap (the first disclosure of the loop)'
    ).toBe(0);

    // (a) The wiped holder must NOT be resurrected by wrapMemberInViaProduction`s
    // empty-holder re-fetch branch.
    expect(
      holder.hasLiveKey(),
      'RE-REVIEW A(a): a holder wiped mid-loop must NOT be resurrected with a live key by wrapMemberInViaProduction`s empty-holder re-fetch (:794 set())'
    ).toBe(false);
    expect(
      holder.isPopulated(),
      'RE-REVIEW A(a): the just-wiped key map must NOT be repopulated by the empty-holder re-fetch inside the step-6 re-wrap loop'
    ).toBe(false);

    // (b) ZERO ciphertext sealed + POSTed off-device after the wipe. The wipe
    // landed during the FIRST disclosure, so EVERY remaining-member wrap_member
    // recorded after it is a post-wipe egress and must never happen.
    const iFirstDisclosure = opIndex(ops, (o) => o.op === 'get_member_pubkey');
    expect(iFirstDisclosure, 'the step-6 loop reached its first disclosure').toBeGreaterThanOrEqual(
      0
    );
    const wrapsAfterWipe = ops
      .map((o, i) => ({ o, i }))
      .filter(({ o, i }) => o.op === 'wrap_member' && i > iFirstDisclosure);
    expect(
      wrapsAfterWipe.length,
      'RE-REVIEW A(b): no member ciphertext may be sealed + POSTed off-device after a mid-loop session-end wipe (the wiped key resurrected and egressed)'
    ).toBe(0);

    // (c) A LOUD non-ok result — a wiped ceremony can never be a success. The
    // self-wrap landed, so the fresh (non-resume) latch-abandon is `incomplete`
    // (resumable), never a silent ok / ok_with_pending.
    expect(
      r.status,
      'RE-REVIEW A(c): a mid-loop session-end wipe must fail LOUD as incomplete, never a silent ok'
    ).toBe('incomplete');
    expect(r.status, 'RE-REVIEW A(c): never ok on a wiped ceremony').not.toBe('ok');
    expect(r.status, 'RE-REVIEW A(c): never ok_with_pending on a wiped ceremony').not.toBe(
      'ok_with_pending'
    );

    // (d) finalize must never run on a wiped ceremony.
    expect(
      ops.some((o) => o.op === 'finalize_rotate'),
      'RE-REVIEW A(d): finalize must NOT be called after a mid-loop session-end wipe'
    ).toBe(false);
  });

  // -------------------------------------------------------------------------
  // RE-REVIEW FINDING B (fail-loud consistency) — a session-end wipe landing
  // AFTER the last re-wrap but BEFORE `finalize` still reports `ok` on a wiped
  // ceremony. The composition re-checks the ENTRY `entryGen` at the step-5 install
  // (:1221) but NOT again before the step-7 finalize (:1303): a wipe landing in
  // the pre-finalize window is never detected, so a wiped ceremony finalizes and
  // returns a clean `ok`.
  //
  // The wipe is injected during the LAST remaining re-wrap's POST await (M2 — the
  // final entry in remaining_members) — strictly AFTER every re-wrap has sealed +
  // landed, strictly BEFORE `finalize` is dispatched (proven by
  // finalizeSeenBeforeWipe===false). A wipe DURING the `finalize` RPC await itself
  // is acceptable-honest (the rotation completed server-side) and is deliberately
  // NOT targeted here. Deterministic (transport/holder hook, no timer).
  // -------------------------------------------------------------------------
  it('RE-REVIEW B (fail-loud): a session-end wipe after the last re-wrap but BEFORE finalize must not report ok on a wiped ceremony — incomplete, holder empty, no finalize', async () => {
    const c = await setupCommittee();
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH }); // step 1 skipped

    let wipeCalls = 0;
    let wrapMemberOpsBeforeWipe = -1;
    let finalizeSeenBeforeWipe = true; // pessimistic default; proven false below
    let wrapMemberSeen = 0;
    let finalizeSeen = false;
    const hooks: TransportHooks = {
      onOp: (op, _occurrence, body) => {
        if (op === 'finalize_rotate') finalizeSeen = true;
        if (op === 'wrap_member') {
          // M2 is LAST in remaining_members [M1, M2], so its re-wrap is the FINAL
          // re-wrap. Fire the wipe during M2's wrap POST — after the self-wrap +
          // M1 re-wrap have already sealed + landed, and strictly BEFORE finalize
          // is dispatched (the before-finalize window; NOT the acceptable-honest
          // during-finalize-await sub-case). The seal for M2 already ran (:896),
          // so M2's wrap lands correctly; only the pre-finalize latch is at issue.
          if (String(body.member_user_id) === M2) {
            wrapMemberOpsBeforeWipe = wrapMemberSeen; // self(0)+M1(1) already POSTed
            finalizeSeenBeforeWipe = finalizeSeen; // must be false — pre-finalize
            holder.onPanicWipe();
            wipeCalls += 1;
          }
          wrapMemberSeen += 1;
        }
      }
    };
    const { transport, ops } = makeTransport(c.srv, hooks);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });

    const r = await runRotation(standardOpts(c, client, holder));

    // Determinism guard — the single wipe landed at the LAST re-wrap (self + M1
    // already POSTed) and strictly BEFORE finalize was dispatched.
    expect(wipeCalls, 'determinism: exactly one wipe was injected at the last re-wrap').toBe(1);
    expect(
      wrapMemberOpsBeforeWipe,
      'determinism: the self-wrap + M1 re-wrap already POSTed before the wipe (the wipe is at the LAST re-wrap)'
    ).toBe(2);
    expect(
      finalizeSeenBeforeWipe,
      'determinism: the wipe landed in the BEFORE-finalize window (finalize not yet dispatched) — not the acceptable during-finalize-await sub-case'
    ).toBe(false);

    // A wiped ceremony is NOT a clean ok — the composition must fail LOUD.
    expect(
      r.status,
      'RE-REVIEW B: a session-end wipe before finalize must return incomplete, never a clean ok on a wiped ceremony'
    ).toBe('incomplete');
    expect(r.status, 'RE-REVIEW B: never ok on a wiped ceremony').not.toBe('ok');
    expect(r.status, 'RE-REVIEW B: never ok_with_pending on a wiped ceremony').not.toBe(
      'ok_with_pending'
    );

    // The holder is empty (the wipe zeroized + cleared the map; nothing resurrected
    // it in the pre-finalize window).
    expect(holder.hasLiveKey(), 'RE-REVIEW B: the wiped holder holds no live key').toBe(false);
    expect(holder.isPopulated(), 'RE-REVIEW B: the wiped key map stays empty (no resurrection)').toBe(
      false
    );

    // finalize must never commit a ceremony wiped before finalize (the before-
    // finalize latch aborts, mirroring the step-5 install latch).
    expect(
      ops.some((o) => o.op === 'finalize_rotate'),
      'RE-REVIEW B: finalize must NOT be dispatched on a ceremony wiped before finalize'
    ).toBe(false);
  });

  // -------------------------------------------------------------------------
  // FINDING 2 (MEDIUM) — revoke-fail after rotate drops the orphan context.
  // After a successful `rotate` (production-flows.ts:1123 — a live zero-wrap
  // epoch is minted), if `revokeCommitteeMember` fails the composition returns a
  // BARE `{status:'failed', reason, http}` (:1135) with NO rotation_id/new_key_id
  // — stranding the orphan epoch (the caller cannot route to abandon+re-drive)
  // AND leaving the removed member's old-epoch wraps in place. A revoke fault
  // after a landed rotate must carry the orphan context, exactly like a failed
  // self-wrap (:1161).
  // -------------------------------------------------------------------------
  it('FINDING 2 (MEDIUM): a revoke_member failure AFTER a landed rotate must carry the orphan context (orphaned + rotation_id + new_key_id), not a bare failed that strands the zero-wrap epoch', async () => {
    const c = await setupCommittee();
    // rotate succeeds (mints a fresh live zero-wrap epoch); revoke_member then
    // fails with a hard server fault.
    const hooks: TransportHooks = {
      override: (op) => (op === 'revoke_member' ? wireErr('revoke_post_failed', 500) : undefined)
    };
    const { transport, ops } = makeTransport(c.srv, hooks);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    const r = await runRotation(standardOpts(c, client, holder));

    // Determinism / precondition — the rotate landed (minting the orphan epoch)
    // and the revoke was the failing op.
    expect(ops.some((o) => o.op === 'rotate'), 'the rotate landed before revoke failed').toBe(true);
    expect(ops.some((o) => o.op === 'revoke_member'), 'the revoke_member op was dispatched').toBe(
      true
    );
    const orphanEpoch = c.srv.liveEpoch()!.key_id; // the new zero-wrap live epoch
    expect(orphanEpoch, 'rotate minted a fresh live epoch (the orphan)').not.toBe(OLD_KEY_ID);

    // The result must carry the orphan context so the caller can retire the
    // zero-wrap epoch and re-drive — a bare `failed` strands it.
    expect(
      r.status,
      'FINDING 2: a revoke-fail after a landed rotate strands a zero-wrap orphan epoch — it must be reported orphaned, not a bare failed'
    ).toBe('orphaned');
    expect(
      r.rotation_id,
      'FINDING 2: orphaned must carry rotation_id so the caller can route to abandon+re-drive'
    ).toBeDefined();
    expect(
      r.new_key_id,
      'FINDING 2: orphaned must carry new_key_id (the orphan epoch) so the caller can retire it'
    ).toBe(orphanEpoch);

    // No self-wrap / no finalize was attempted on the orphan epoch.
    expect(ops.some((o) => o.op === 'wrap_member'), 'no wrap POSTed after a failed revoke').toBe(
      false
    );
    expect(
      ops.some((o) => o.op === 'finalize_rotate'),
      'no finalize on a zero-wrap orphan epoch'
    ).toBe(false);

    // Documentation of the orphan state: the failed revoke left the removed
    // member's old-epoch wrap in place — the orphan context is what lets the
    // caller drive the purge on re-drive.
    expect(
      c.srv.wrapOn(REMOVED, OLD_KEY_ID),
      'the failed revoke left the removed member`s old-epoch wrap un-purged (orphan state the caller must clean up)'
    ).toBeDefined();
  });

  // -------------------------------------------------------------------------
  // FINDING 3 (MEDIUM) — no fail-before-mutate on a malformed actor_public_key.
  // The sibling init guards `actor_public_key.length !== 32` BEFORE every
  // state-mutating RPC (production-flows.ts:277 / :328 / :397), returning
  // {status:'failed', reason:'invalid_input', http:422}. The rotation
  // composition has NO such entry guard: it lands `rotate` (:1123) + `revoke`
  // (:1134) FIRST, then throws in `crypto_box_seal` (:1146) → caught → `orphaned`
  // (:1150). A persistent bad pubkey is an epoch-churn livelock (every re-drive
  // mints + strands another epoch).
  // -------------------------------------------------------------------------
  it('FINDING 3 (MEDIUM): a malformed actor_public_key (length !== 32) must fail BEFORE any state-mutating RPC with failed/invalid_input/422 (the sibling init shape), not land rotate+revoke then throw into orphaned', async () => {
    const c = await setupCommittee();
    const { transport, ops } = makeTransport(c.srv);
    const client = new SupabaseT07Client({ transport, localIdentity: c.localIdentity });
    const holder = new CommitteeKeyHolder();
    holder.set({ data_key: c.oldKey, key_id: OLD_KEY_ID, epoch: OLD_EPOCH });

    // A malformed (non-32-byte) actor pubkey — `crypto_box_seal` would throw, but
    // the guard must trip BEFORE any state mutation (F-138 fail-before-mutate).
    const badPubkey = new Uint8Array(31);

    const r = await runRotation(standardOpts(c, client, holder, { actor_public_key: badPubkey }));

    // Fail-before-mutate: NO state-mutating RPC may be issued.
    expect(
      ops.some((o) => o.op === 'rotate'),
      'FINDING 3: a malformed actor_public_key must NOT land a rotate (validate BEFORE any state mutation)'
    ).toBe(false);
    expect(
      ops.some((o) => o.op === 'revoke_member'),
      'FINDING 3: a malformed actor_public_key must NOT revoke'
    ).toBe(false);
    expect(
      ops.some((o) => o.op === 'wrap_member'),
      'FINDING 3: a malformed actor_public_key must NOT wrap'
    ).toBe(false);
    expect(
      c.srv.epochs.length,
      'FINDING 3: no epoch may be minted by an invalid-input rotation (no epoch-churn livelock)'
    ).toBe(1);

    // The result matches the sibling init guard shape exactly.
    expect(
      r.status,
      'FINDING 3: an invalid actor pubkey must be a typed failed (matching the sibling init), never orphaned'
    ).toBe('failed');
    expect(r.reason, 'FINDING 3: reason mirrors the sibling init guard (invalid_input)').toBe(
      'invalid_input'
    );
    expect(r.http, 'FINDING 3: http mirrors the sibling init guard (422)').toBe(422);
  });
});
